### ISSUE TITLE
Update for tensorflow 0.12?

### ISSUE THREAD

**Issue by pgulley** [yenchenlin/pix2pix-tensorflow#6]
Using the default tensorflow installation (ie, pip install tensorflow, as of 12/10/16, which yeilds 0.12.0RC0), training the pix2pix model fails with an error:

```
COMP:pix2pix-tensorflow usr$ python main.py --phase train
Traceback (most recent call last):
  File "main.py", line 58, in <module>
    tf.app.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "main.py", line 50, in main
    checkpoint_dir=args.checkpoint_dir, sample_dir=args.sample_dir)
  File "/Users/usr/Desktop/camera_vr/deep_pic/pix2pix-tensorflow/model.py", line 67, in __init__
    self.build_model()
  File "/Users/usr/Desktop/camera_vr/deep_pic/pix2pix-tensorflow/model.py", line 83, in build_model
    self.D_, self.D_logits_ = self.discriminator(self.fake_AB, reuse=True)
  File "/Users/usr/Desktop/camera_vr/deep_pic/pix2pix-tensorflow/model.py", line 205, in discriminator
    h1 = lrelu(self.d_bn1(conv2d(h0, self.df_dim*2, name='d_h1_conv')))
  File "/Users/usr/Desktop/camera_vr/deep_pic/pix2pix-tensorflow/ops.py", line 34, in __call__
    ema_apply_op = self.ema.apply([batch_mean, batch_var])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 391, in apply
    self._averages[var], var, decay, zero_debias=zero_debias))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 70, in assign_moving_average
    update_delta = _zero_debias(variable, value, decay)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/training/moving_averages.py", line 177, in _zero_debias
    trainable=False)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1024, in get_variable
    custom_getter=custom_getter)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 850, in get_variable
    custom_getter=custom_getter)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 346, in get_variable
    validate_shape=validate_shape)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 331, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 650, in _get_single_variable
    "VarScope?" % name)
ValueError: Variable d_bn1/d_bn1_2/d_bn1_2/moments/moments_1/mean/ExponentialMovingAverage/biased does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?
```

**Comment by yenchenlin** [comment]
Hello, thanks for the notification.
I will look into this.

**Comment by eyaler** [comment]
https://github.com/tensorflow/tensorflow/issues/2740
https://github.com/carpedm20/DCGAN-tensorflow/issues/59
https://github.com/iamaaditya/DCGAN-tensorflow/commit/b9299ae1b2c92a176f4cab511672262663f0fadf

**Comment by Neltherion** [comment]
First, Thanks for the time you're putting into this, and Second, I'm having the same problem on TensorFlow 0.12 Running in Windows GPU Mode...

**Comment by Neltherion** [comment]
@eyaler the fix for batch_norm you mentioned worked for me... thanks

**Comment by spk921** [comment]
So is this working with tf0.12?

**Comment by nightrome** [comment]
Yes the latest version works fine on 0.12.
